name: mp3_player
description: "Thence mp3 Player"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  just_audio: ^0.9.18
  flutter_bloc: ^8.1.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  dio: ^5.2.0
  json_annotation: ^4.8.0
  permission_handler: ^10.4.0
  path: ^1.9.0
  ffmpeg_kit_flutter: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: 9.1.3
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/play.png
    - assets/pause.png